### ISSUE TITLE
Cannot resolve symbol 'R'

### ISSUE THREAD

**Issue by Michalixx** [Emil333/TournamentBrackets#7]
Stack trace: https://pastebin.com/3qt9VK7p 

Every import with R at the end of it (import androidx.appcompat.R; or import androidx.fragment.R;) doesn't work (Cannot resolve symbol 'R'). 
![issuegit](https://user-images.githubusercontent.com/67645372/130323503-3188f2fb-ebda-4ac2-8d6f-e26558ef2a37.png)

**Comment by emil-ep** [comment]
@Michalixx Try cleaning gradle and build again. This doesn't seem to be an issue with package, could be related to android studio or gradle cache.
